name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch: # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Add upstream remote
        run: git remote add upstream https://github.com/original/repo.git
      - name: Fetch upstream
        run: git fetch upstream
      - name: Merge upstream -> main
        run: git merge upstream/main --allow-unrelated-histories || true
      - name: Push changes
        run: git push origin main
